Repository MLH-Fellowship/recycle-this, pull requests merged in 2020-10, with the labels that each got.

#36 Add Leaderboard with username
  Game.js
  GameOver.js
  StartScreen.js
  package.json
  src/renderers.js
  src/screens/Game.js
  src/screens/GameOver.js
  yarn.lock
Labels: Backend

#40 Leaderboard render
  package-lock.json
  src/renderers.js
  src/screens/Game.js
  src/screens/GameOver.js
Labels: Backend, Frontend

#42 Frontend modal
  package.json
  src/assets/trophy.png
  src/screens/Game.js
  src/screens/GameOver.js
  yarn.lock
Labels: Frontend

#43 Added floor, centered timer, positioned score to the right of the screen
  package-lock.json
  src/assets/floor.png
  src/assets/floor2.png
  src/renderers.js
  src/screens/Game.js
  src/screens/StartScreen.js
Labels: Frontend
